// Package cedar contains a Go port of the Cedar/Mesa lexer and token
// definitions from Rochus Keller's TiogaViewer (originally C++/Qt).
//
// tokentype.go ports CedarTokenType.{h,cpp}. The original file was generated by
// EbnfStudio as a large character trie; here the equivalent behaviour is
// expressed as a keyword table plus a compact operator matcher. The enum order
// is preserved exactly so the literal/keyword/special range predicates match.
package cedar

// TokenType enumerates every terminal the lexer can produce. The ordering is
// identical to the original enum so that the TT_* markers keep delimiting the
// literal, keyword and special ranges.
type TokenType int

const (
	Tok_Invalid TokenType = iota

	TT_Literals
	Tok_Bang
	Tok_Hash
	Tok_Lpar
	Tok_Rpar
	Tok_Star
	Tok_Plus
	Tok_Comma
	Tok_Minus
	Tok_2Minus
	Tok_Dot
	Tok_2Dot
	Tok_Slash
	Tok_Colon
	Tok_Semi
	Tok_Lt
	Tok_2Lt
	Tok_Leq
	Tok_Eq
	Tok_EqGt
	Tok_Gt
	Tok_Geq
	Tok_2Gt
	Tok_At
	Tok_Lbrack
	Tok_Rbrack
	Tok_Hat
	Tok_Lbrace
	Tok_Bar
	Tok_Rbrace
	Tok_Tilde
	Tok_TildeLt
	Tok_TildeEq
	Tok_TildeGt
	Tok_2Tilde
	Tok_2190 // the left-arrow assignment token

	TT_Keywords
	Tok_ABS
	Tok_ALL
	Tok_AND
	Tok_ANY
	Tok_APPLY
	Tok_ARRAY
	Tok_BASE
	Tok_BEGIN
	Tok_BROADCAST
	Tok_CEDAR
	Tok_CHECKED
	Tok_CODE
	Tok_COMPUTED
	Tok_CONS
	Tok_CONTINUE
	Tok_DECREASING
	Tok_DEFINITIONS
	Tok_DEPENDENT
	Tok_DESCRIPTOR
	Tok_DIRECTORY
	Tok_DO
	Tok_ELSE
	Tok_ENABLE
	Tok_END
	Tok_ENDCASE
	Tok_ENDLOOP
	Tok_ENTRY
	Tok_ERROR
	Tok_EXIT
	Tok_EXITS
	Tok_EXPORTS
	Tok_FINISHED
	Tok_FIRST
	Tok_FOR
	Tok_FORK
	Tok_FRAME
	Tok_FREE
	Tok_FROM
	Tok_GO
	Tok_GOTO
	Tok_IF
	Tok_IMPORTS
	Tok_IN
	Tok_INLINE
	Tok_INTERNAL
	Tok_ISTYPE
	Tok_JOIN
	Tok_LAST
	Tok_LENGTH
	Tok_LIST
	Tok_LOCKS
	Tok_LONG
	Tok_LOOP
	Tok_LOOPHOLE
	Tok_MACHINE
	Tok_MAX
	Tok_MIN
	Tok_MOD
	Tok_MONITOR
	Tok_MONITORED
	Tok_NARROW
	Tok_NEW
	Tok_NIL
	Tok_NOT
	Tok_NOTIFY
	Tok_NULL
	Tok_OF
	Tok_OPEN
	Tok_OR
	Tok_ORD
	Tok_ORDERED
	Tok_OVERLAID
	Tok_PACKED
	Tok_PAINTED
	Tok_POINTER
	Tok_PORT
	Tok_PRED
	Tok_PRIVATE
	Tok_PROC
	Tok_PROCEDURE
	Tok_PROCESS
	Tok_PROGRAM
	Tok_PUBLIC
	Tok_READONLY
	Tok_RECORD
	Tok_REF
	Tok_REJECT
	Tok_RELATIVE
	Tok_REPEAT
	Tok_RESTART
	Tok_RESUME
	Tok_RETRY
	Tok_RETURN
	Tok_RETURNS
	Tok_SAFE
	Tok_SELECT
	Tok_SEQUENCE
	Tok_SHARES
	Tok_SIGNAL
	Tok_SIZE
	Tok_START
	Tok_STATE
	Tok_STOP
	Tok_SUCC
	Tok_THEN
	Tok_THROUGH
	Tok_TO
	Tok_TRANSFER
	Tok_TRASH
	Tok_TRUSTED
	Tok_TYPE
	Tok_UNCHECKED
	Tok_UNCOUNTED
	Tok_UNSAFE
	Tok_UNTIL
	Tok_USING
	Tok_VAL
	Tok_VAR
	Tok_WAIT
	Tok_WHILE
	Tok_WITH
	Tok_ZONE

	TT_Specials
	Tok_number
	Tok_string
	Tok_char
	Tok_symbol
	Tok_n // a plain identifier
	Tok_Comment
	Tok_Eof

	TT_MaxToken
	TT_Max
)

// IsLiteral reports whether t is one of the punctuation/operator tokens.
func IsLiteral(t TokenType) bool { return t > TT_Literals && t < TT_Keywords }

// IsKeyword reports whether t is one of the reserved Cedar/Mesa keywords.
func IsKeyword(t TokenType) bool { return t > TT_Keywords && t < TT_Specials }

// IsSpecial reports whether t is one of the special tokens (number, string, …).
func IsSpecial(t TokenType) bool { return t > TT_Specials && t < TT_MaxToken }

// keywords maps a keyword's exact spelling to its token type. The lexer only
// treats a maximal identifier as a keyword when the whole identifier matches,
// mirroring the original's post-match length check.
var keywords = map[string]TokenType{
	"ABS": Tok_ABS, "ALL": Tok_ALL, "AND": Tok_AND, "ANY": Tok_ANY,
	"APPLY": Tok_APPLY, "ARRAY": Tok_ARRAY, "BASE": Tok_BASE, "BEGIN": Tok_BEGIN,
	"BROADCAST": Tok_BROADCAST, "CEDAR": Tok_CEDAR, "CHECKED": Tok_CHECKED,
	"CODE": Tok_CODE, "COMPUTED": Tok_COMPUTED, "CONS": Tok_CONS,
	"CONTINUE": Tok_CONTINUE, "DECREASING": Tok_DECREASING,
	"DEFINITIONS": Tok_DEFINITIONS, "DEPENDENT": Tok_DEPENDENT,
	"DESCRIPTOR": Tok_DESCRIPTOR, "DIRECTORY": Tok_DIRECTORY, "DO": Tok_DO,
	"ELSE": Tok_ELSE, "ENABLE": Tok_ENABLE, "END": Tok_END, "ENDCASE": Tok_ENDCASE,
	"ENDLOOP": Tok_ENDLOOP, "ENTRY": Tok_ENTRY, "ERROR": Tok_ERROR, "EXIT": Tok_EXIT,
	"EXITS": Tok_EXITS, "EXPORTS": Tok_EXPORTS, "FINISHED": Tok_FINISHED,
	"FIRST": Tok_FIRST, "FOR": Tok_FOR, "FORK": Tok_FORK, "FRAME": Tok_FRAME,
	"FREE": Tok_FREE, "FROM": Tok_FROM, "GO": Tok_GO, "GOTO": Tok_GOTO, "IF": Tok_IF,
	"IMPORTS": Tok_IMPORTS, "IN": Tok_IN, "INLINE": Tok_INLINE,
	"INTERNAL": Tok_INTERNAL, "ISTYPE": Tok_ISTYPE, "JOIN": Tok_JOIN,
	"LAST": Tok_LAST, "LENGTH": Tok_LENGTH, "LIST": Tok_LIST, "LOCKS": Tok_LOCKS,
	"LONG": Tok_LONG, "LOOP": Tok_LOOP, "LOOPHOLE": Tok_LOOPHOLE,
	"MACHINE": Tok_MACHINE, "MAX": Tok_MAX, "MIN": Tok_MIN, "MOD": Tok_MOD,
	"MONITOR": Tok_MONITOR, "MONITORED": Tok_MONITORED, "NARROW": Tok_NARROW,
	"NEW": Tok_NEW, "NIL": Tok_NIL, "NOT": Tok_NOT, "NOTIFY": Tok_NOTIFY,
	"NULL": Tok_NULL, "OF": Tok_OF, "OPEN": Tok_OPEN, "OR": Tok_OR, "ORD": Tok_ORD,
	"ORDERED": Tok_ORDERED, "OVERLAID": Tok_OVERLAID, "PACKED": Tok_PACKED,
	"PAINTED": Tok_PAINTED, "POINTER": Tok_POINTER, "PORT": Tok_PORT,
	"PRED": Tok_PRED, "PRIVATE": Tok_PRIVATE, "PROC": Tok_PROC,
	"PROCEDURE": Tok_PROCEDURE, "PROCESS": Tok_PROCESS, "PROGRAM": Tok_PROGRAM,
	"PUBLIC": Tok_PUBLIC, "READONLY": Tok_READONLY, "RECORD": Tok_RECORD,
	"REF": Tok_REF, "REJECT": Tok_REJECT, "RELATIVE": Tok_RELATIVE,
	"REPEAT": Tok_REPEAT, "RESTART": Tok_RESTART, "RESUME": Tok_RESUME,
	"RETRY": Tok_RETRY, "RETURN": Tok_RETURN, "RETURNS": Tok_RETURNS,
	"SAFE": Tok_SAFE, "SELECT": Tok_SELECT, "SEQUENCE": Tok_SEQUENCE,
	"SHARES": Tok_SHARES, "SIGNAL": Tok_SIGNAL, "SIZE": Tok_SIZE, "START": Tok_START,
	"STATE": Tok_STATE, "STOP": Tok_STOP, "SUCC": Tok_SUCC, "THEN": Tok_THEN,
	"THROUGH": Tok_THROUGH, "TO": Tok_TO, "TRANSFER": Tok_TRANSFER,
	"TRASH": Tok_TRASH, "TRUSTED": Tok_TRUSTED, "TYPE": Tok_TYPE,
	"UNCHECKED": Tok_UNCHECKED, "UNCOUNTED": Tok_UNCOUNTED, "UNSAFE": Tok_UNSAFE,
	"UNTIL": Tok_UNTIL, "USING": Tok_USING, "VAL": Tok_VAL, "VAR": Tok_VAR,
	"WAIT": Tok_WAIT, "WHILE": Tok_WHILE, "WITH": Tok_WITH, "ZONE": Tok_ZONE,
}

// keywordType returns the keyword token type for an exact identifier spelling,
// or Tok_Invalid if the identifier is not a keyword.
func keywordType(ident string) TokenType {
	if t, ok := keywords[ident]; ok {
		return t
	}
	return Tok_Invalid
}

// matchOperator matches the longest punctuation/operator token starting at
// s[pos]. It returns the token type and the position just past the match, or
// (Tok_Invalid, pos) if nothing matches. This mirrors tokenTypeFromString for
// the non-alphanumeric case the lexer relies on.
func matchOperator(s []byte, pos int) (TokenType, int) {
	at := func(i int) byte {
		if i >= 0 && i < len(s) {
			return s[i]
		}
		return 0
	}
	i := pos
	switch at(i) {
	case '!':
		return Tok_Bang, i + 1
	case '#':
		return Tok_Hash, i + 1
	case '(':
		return Tok_Lpar, i + 1
	case ')':
		return Tok_Rpar, i + 1
	case '*':
		return Tok_Star, i + 1
	case '+':
		return Tok_Plus, i + 1
	case ',':
		return Tok_Comma, i + 1
	case '-':
		if at(i+1) == '-' {
			return Tok_2Minus, i + 2
		}
		return Tok_Minus, i + 1
	case '.':
		if at(i+1) == '.' {
			return Tok_2Dot, i + 2
		}
		return Tok_Dot, i + 1
	case '/':
		return Tok_Slash, i + 1
	case ':':
		return Tok_Colon, i + 1
	case ';':
		return Tok_Semi, i + 1
	case '<':
		switch at(i + 1) {
		case '<':
			return Tok_2Lt, i + 2
		case '=':
			return Tok_Leq, i + 2
		}
		return Tok_Lt, i + 1
	case '=':
		if at(i+1) == '>' {
			return Tok_EqGt, i + 2
		}
		return Tok_Eq, i + 1
	case '>':
		switch at(i + 1) {
		case '=':
			return Tok_Geq, i + 2
		case '>':
			return Tok_2Gt, i + 2
		}
		return Tok_Gt, i + 1
	case '@':
		return Tok_At, i + 1
	case '[':
		return Tok_Lbrack, i + 1
	case ']':
		return Tok_Rbrack, i + 1
	case '^':
		return Tok_Hat, i + 1
	case '{':
		return Tok_Lbrace, i + 1
	case '|':
		return Tok_Bar, i + 1
	case '}':
		return Tok_Rbrace, i + 1
	case '~':
		switch at(i + 1) {
		case '<':
			return Tok_TildeLt, i + 2
		case '=':
			return Tok_TildeEq, i + 2
		case '>':
			return Tok_TildeGt, i + 2
		case '~':
			return Tok_2Tilde, i + 2
		}
		return Tok_Tilde, i + 1
	}
	return Tok_Invalid, pos
}
